#
# f argument passing
#
errors = 0
print("Testing function arguments...")

f = fn (a: int, b: int, c: int, d: int)
    v = a + b + c + d

g = fn () { # empty argument list
    return # BUG! must have braces with 'return' - probably due to stack unwinding from exception
}

a = 1
b = 2
try assert f(a: 1, b: 2, c: 3, d: 4) == 10 rescue errors++
try assert f(1, 2, 3, 4) == 10 rescue errors++
try assert f(1, 2, c: 3, d: 4) == 10 rescue errors++
try assert f(a, b, b + 1, d: b * 2) == 10 rescue errors++

try assert f( # complex expression
    a: 1,
    b: 2,
    c: 3,
    d: for i in 1 to 4 i
) == 10
rescue errors++

try assert f( # complex expression
    a: 1,
    b: 2,
    c: 3,
    d: if a == 1 for i in 1 to 4 i
) == 10
rescue errors++

try assert g() == nil rescue errors++
try assert g(1) == nil rescue nil else errors++

print(if errors "Some fs failed ({errors}) errors\n" else "passed!\n")

